### ISSUE TITLE
Support per-scenario defaults

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/gdt-core#2]
We need to support a hierarchy of defaults, particularly for things like timeouts. A scenario's timeout defaults can be overridden by a test spec's timeout values, etc.

`example-scenario.yaml`
```yaml
name: example scenario with defaults and overrides for timeouts
defaults:
  # This is the default timeout value for test specs in the scenario
  timeout:
    after: 2s
tests:
 - name: test with timeout override
   timeout:
     after: 1s
 - name: test which uses scenario default timeout
```
