### ISSUE TITLE
Support `timeout.after` shortcut parsing

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/gdt-core#3]
Having to write:

```yaml
tests:
 - exec: sleep 1
   timeout:
     after: 2s
```

is verbose. We should support a pithier:

```yaml
tests:
 - exec: sleep 1
   timeout.after: 2s
```
